export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';
export const USER_LOGGED_IN_FAIL = 'USER_LOGGED_IN_FAIL';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
